import AppKit
import Combine
import UniformTypeIdentifiers

/// Watches the general pasteboard and keeps a deduplicated, persisted history.
@MainActor
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    /// Called when a brand-new item is captured from another app (not our own writes).
    var onCapture: ((ClipboardItem) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    private var maxItems: Int { max(AppSettings.shared.maxItems, 20) }

    /// Pasteboard markers set by password managers and transient producers.
    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.apple.is-sensitive")
    ]

    private struct ImageFormatInfo {
        let type: NSPasteboard.PasteboardType
        let ext: String
    }

    private static let imageFormats: [ImageFormatInfo] = [
        ImageFormatInfo(type: .init("org.webmproject.webp"), ext: "webp"),
        ImageFormatInfo(type: .init("public.heic"), ext: "heic"),
        ImageFormatInfo(type: .init("com.compuserve.gif"), ext: "gif"),
        ImageFormatInfo(type: .init("public.jpeg"), ext: "jpg"),
        ImageFormatInfo(type: .png, ext: "png"),
        ImageFormatInfo(type: .tiff, ext: "tiff")
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
        loadFromDisk()
    }

    private var cleanupTimer: Timer?

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let t = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t

        // Apply the retention rule immediately and then on a slow cadence.
        purgeExpired()
        let c = Timer.scheduledTimer(withTimeInterval: 60, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.purgeExpired() }
        }
        RunLoop.main.add(c, forMode: .common)
        cleanupTimer = c
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        cleanupTimer?.invalidate()
        cleanupTimer = nil
    }

    /// Writes an item back to the pasteboard (used when a card is clicked).
    func copyToPasteboard(_ item: ClipboardItem) {
        let prevClipboard = pasteboard.string(forType: .string) ?? ""
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link, .color:
            if let text = item.text {
                let resolved = resolveTemplates(text, prevClipboard: prevClipboard)
                pasteboard.setString(resolved, forType: .string)
            }
        case .image:
            if let url = item.fileURL, let data = try? Data(contentsOf: url),
               let image = NSImage(contentsOf: url) {
                let ext = url.pathExtension.lowercased()
                
                let nativeType: NSPasteboard.PasteboardType
                switch ext {
                case "png": nativeType = .png
                case "jpg", "jpeg": nativeType = .init("public.jpeg")
                case "gif": nativeType = .init("com.compuserve.gif")
                case "heic": nativeType = .init("public.heic")
                case "webp": nativeType = .init("org.webmproject.webp")
                case "tiff", "tif": nativeType = .tiff
                default: nativeType = .png
                }
                
                var declaredTypes: [NSPasteboard.PasteboardType] = [nativeType]
                if nativeType != .png { declaredTypes.append(.png) }
                if nativeType != .tiff { declaredTypes.append(.tiff) }
                
                pasteboard.declareTypes(declaredTypes, owner: nil)
                pasteboard.setData(data, forType: nativeType)
                
                if nativeType != .png {
                    if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
                        let rep = NSBitmapImageRep(cgImage: cgImage)
                        rep.size = image.size
                        if let pngData = rep.representation(using: .png, properties: [:]) {
                            pasteboard.setData(pngData, forType: .png)
                        }
                    }
                }
                
                if nativeType != .tiff {
                    if let tiffData = image.tiffRepresentation {
                        pasteboard.setData(tiffData, forType: .tiff)
                    }
                }
            }
        case .file:
            if let url = item.fileURL { pasteboard.writeObjects([url as NSURL]) }
        }
        // Avoid re-capturing our own write.
        lastChangeCount = pasteboard.changeCount
    }

    /// Writes only the item's plain-text payload to the pasteboard, stripping any
    /// rich representation. For files this copies the path as text.
    func copyAsPlainText(_ item: ClipboardItem) {
        guard let text = item.text else { return }
        let prevClipboard = pasteboard.string(forType: .string) ?? ""
        let resolved = resolveTemplates(text, prevClipboard: prevClipboard)
        copyString(resolved)
    }

    private func resolveTemplates(_ text: String, prevClipboard: String) -> String {
        var resolved = text

        // 1. Resolve {date}
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let dateStr = dateFormatter.string(from: Date())
        resolved = resolved.replacingOccurrences(of: "{date}", with: dateStr)

        // 2. Resolve {time}
        let timeFormatter = DateFormatter()
        timeFormatter.dateFormat = "HH:mm"
        let timeStr = timeFormatter.string(from: Date())
        resolved = resolved.replacingOccurrences(of: "{time}", with: timeStr)

        // 3. Resolve {clipboard}
        resolved = resolved.replacingOccurrences(of: "{clipboard}", with: prevClipboard)

        return resolved
    }

    /// Writes a raw string to the pasteboard as plain text.
    func copyString(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    /// Replaces an item's text in place (used by quick transforms) and persists.
    /// `kind` is immutable, so only the payload text changes.
    func updateText(_ newText: String, for item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        guard items[idx].text != newText else { return }
        items[idx].text = newText
        persist()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        if let url = item.fileURL, item.kind != .file {
            try? FileManager.default.removeItem(at: url)
            let parentDir = url.deletingLastPathComponent()
            if parentDir.lastPathComponent == item.id.uuidString {
                try? FileManager.default.removeItem(at: parentDir)
            }
        }
        persist()
    }

    func clearAll() {
        for item in items where item.fileURL != nil {
            if let url = item.fileURL, item.kind != .file {
                try? FileManager.default.removeItem(at: url)
                let parentDir = url.deletingLastPathComponent()
                if parentDir.lastPathComponent == item.id.uuidString {
                    try? FileManager.default.removeItem(at: parentDir)
                }
            }
        }
        items.removeAll()
        persist()
    }

    // MARK: - Polling

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard let item = captureCurrent() else { return }
        insert(item)
    }

    private func captureCurrent() -> ClipboardItem? {
        // Respect privacy: skip content marked sensitive/transient.
        if AppSettings.shared.skipSensitive, isSensitive() {
            return nil
        }

        let app = NSWorkspace.shared.frontmostApplication
        let appName = app?.localizedName
        let appIcon = app?.icon

        // 1. File URLs.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], let first = urls.first {
            return ClipboardItem(
                kind: .file,
                text: first.path,
                fileURL: first,
                sourceAppName: appName,
                sourceAppIcon: appIcon
            )
        }

        // 2. Images.
        if let types = pasteboard.types,
           types.contains(where: { t in
               Self.imageFormats.contains(where: { $0.type == t })
           }),
           !types.contains(where: { $0 == .rtf || $0 == .rtfd }) {
            let itemId = UUID()
            if let url = cacheImageFromPasteboard(itemId: itemId) {
                return ClipboardItem(
                    id: itemId,
                    kind: .image,
                    fileURL: url,
                    sourceAppName: appName,
                    sourceAppIcon: appIcon
                )
            }
        }

        // 3. Text (and derived link / color).
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind = classifyText(string)
            return ClipboardItem(
                kind: kind,
                text: string,
                sourceAppName: appName,
                sourceAppIcon: appIcon
            )
        }

        return nil
    }

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0) }
    }

    func toggleFavorite(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].isFavorite.toggle()
        persist()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].isPinned.toggle()
        persist()
    }

    /// Creates a pinned text snippet (signature, address, code, …) that stays put
    /// and never gets trimmed or auto-deleted.
    @discardableResult
    func addSnippet(_ text: String) -> ClipboardItem? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        let item = ClipboardItem(
            kind: classifyText(trimmed),
            text: text,
            sourceAppName: "NotchBoard",
            isPinned: true
        )
        items.insert(item, at: 0)
        persist()
        return item
    }

    /// Removes non-pinned, non-favorite items older than the configured retention
    /// window. A window of 0 means "keep forever".
    func purgeExpired() {
        let minutes = AppSettings.shared.autoDeleteMinutes
        guard minutes > 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(minutes) * 60)
        var changed = false
        items.removeAll { item in
            guard !item.isPinned, !item.isFavorite, item.createdAt < cutoff else { return false }
            if let url = item.fileURL, item.kind != .file { try? FileManager.default.removeItem(at: url) }
            changed = true
            return true
        }
        if changed { persist() }
    }

    func addTag(_ tag: String, to item: ClipboardItem) {
        let clean = tag.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty, let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        if !items[idx].tags.contains(where: { $0.caseInsensitiveCompare(clean) == .orderedSame }) {
            items[idx].tags.append(clean)
            persist()
        }
    }

    func removeTag(_ tag: String, from item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].tags.removeAll { $0 == tag }
        persist()
    }

    /// All distinct tags currently in use, sorted.
    var allTags: [String] {
        var seen = Set<String>()
        var result: [String] = []
        for item in items {
            for tag in item.tags where !seen.contains(tag.lowercased()) {
                seen.insert(tag.lowercased())
                result.append(tag)
            }
        }
        return result.sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
    }

    private func classifyText(_ text: String) -> ClipboardItem.Kind {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if NSColor.looksLikeColor(trimmed) { return .color }
        if let url = URL(string: trimmed),
           let scheme = url.scheme,
           ["http", "https"].contains(scheme.lowercased()),
           !trimmed.contains(" ") {
            return .link
        }
        return .text
    }

    private func insert(_ item: ClipboardItem) {
        // Deduplicate consecutive identical text payloads.
        if let text = item.text, let first = items.first,
           first.text == text, first.kind == item.kind {
            return
        }
        items.insert(item, at: 0)
        trimIfNeeded()
        persist()
        onCapture?(item)
    }

    /// Trims to maxItems but never drops favorites or pinned snippets.
    private func trimIfNeeded() {
        guard items.count > maxItems else { return }
        var kept: [ClipboardItem] = []
        var trimmableCount = 0
        for item in items {
            if item.isFavorite || item.isPinned {
                kept.append(item)
            } else if trimmableCount < maxItems {
                kept.append(item)
                trimmableCount += 1
            } else if let url = item.fileURL, item.kind != .file {
                try? FileManager.default.removeItem(at: url)
                let parentDir = url.deletingLastPathComponent()
                if parentDir.lastPathComponent == item.id.uuidString {
                    try? FileManager.default.removeItem(at: parentDir)
                }
            }
        }
        items = kept
    }

    private func getOriginalImageName(ext: String) -> String {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let first = urls.first {
            let lastComponent = first.lastPathComponent
            if !lastComponent.isEmpty && lastComponent != "/" {
                let base = (lastComponent as NSString).deletingPathExtension
                return "\(base).\(ext)"
            }
        }
        return "image-\(Int(Date().timeIntervalSince1970)).\(ext)"
    }

    private func cacheImageFromPasteboard(itemId: UUID) -> URL? {
        var data: Data?
        var ext = "png"
        
        for format in Self.imageFormats {
            if let pasteboardData = pasteboard.data(forType: format.type), !pasteboardData.isEmpty {
                data = pasteboardData
                ext = format.ext
                break
            }
        }
        
        let filename = getOriginalImageName(ext: ext)
        let itemDir = Persistence.cacheDirectory.appendingPathComponent(itemId.uuidString, isDirectory: true)
        Persistence.ensureDirectory(itemDir)
        let url = itemDir.appendingPathComponent(filename)
        
        if let finalData = data {
            do {
                try finalData.write(to: url)
                return url
            } catch {
                print("Failed to write clipboard image data: \(error)")
            }
        }
        
        if let images = pasteboard.readObjects(forClasses: [NSImage.self]) as? [NSImage],
           let image = images.first {
            if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
                let rep = NSBitmapImageRep(cgImage: cgImage)
                rep.size = image.size
                if let pngData = rep.representation(using: .png, properties: [:]) {
                    do {
                        try pngData.write(to: url)
                        return url
                    } catch {
                        print("Failed to write fallback clipboard image: \(error)")
                    }
                }
            }
        }
        
        return nil
    }

    // MARK: - Persistence

    private struct StoredItem: Codable {
        let id: UUID
        let kind: ClipboardItem.Kind
        let createdAt: Date
        let text: String?
        let fileName: String?
        var isFavorite: Bool = false
        var isPinned: Bool = false
        var tags: [String] = []
    }

    private func persist() {
        let stored = items.map { item in
            StoredItem(
                id: item.id,
                kind: item.kind,
                createdAt: item.createdAt,
                text: item.text,
                fileName: item.fileURL?.lastPathComponent,
                isFavorite: item.isFavorite,
                isPinned: item.isPinned,
                tags: item.tags
            )
        }
        Persistence.save(stored, to: Persistence.historyIndexURL)
    }

    private func loadFromDisk() {
        guard let stored = Persistence.load([StoredItem].self, from: Persistence.historyIndexURL) else {
            return
        }
        items = stored.compactMap { s in
            var fileURL: URL?
            if let name = s.fileName {
                let flatCandidate = Persistence.cacheDirectory.appendingPathComponent(name)
                if FileManager.default.fileExists(atPath: flatCandidate.path) {
                    fileURL = flatCandidate
                } else {
                    let nestedCandidate = Persistence.cacheDirectory.appendingPathComponent(s.id.uuidString).appendingPathComponent(name)
                    if FileManager.default.fileExists(atPath: nestedCandidate.path) {
                        fileURL = nestedCandidate
                    }
                }
            }
            // Drop entries whose cached file vanished.
            if (s.kind == .image || s.kind == .file) && fileURL == nil { return nil }
            return ClipboardItem(
                id: s.id,
                kind: s.kind,
                createdAt: s.createdAt,
                text: s.text,
                fileURL: fileURL,
                isFavorite: s.isFavorite,
                isPinned: s.isPinned,
                tags: s.tags
            )
        }
    }
}
