import AppKit
import Combine
import UniformTypeIdentifiers

/// Watches the general pasteboard and keeps a deduplicated, persisted history.
@MainActor
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    /// Called when a brand-new item is captured from another app (not our own writes).
    var onCapture: ((ClipboardItem) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    private var maxItems: Int { max(AppSettings.shared.maxItems, 20) }

    /// Pasteboard markers set by password managers and transient producers.
    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.apple.is-sensitive")
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
        loadFromDisk()
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let t = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Writes an item back to the pasteboard (used when a card is clicked).
    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link, .color:
            if let text = item.text { pasteboard.setString(text, forType: .string) }
        case .image:
            if let url = item.fileURL, let image = NSImage(contentsOf: url) {
                pasteboard.writeObjects([image])
            }
        case .file:
            if let url = item.fileURL { pasteboard.writeObjects([url as NSURL]) }
        }
        // Avoid re-capturing our own write.
        lastChangeCount = pasteboard.changeCount
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        if let url = item.fileURL { try? FileManager.default.removeItem(at: url) }
        persist()
    }

    func clearAll() {
        for item in items where item.fileURL != nil {
            try? FileManager.default.removeItem(at: item.fileURL!)
        }
        items.removeAll()
        persist()
    }

    // MARK: - Polling

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard let item = captureCurrent() else { return }
        insert(item)
    }

    private func captureCurrent() -> ClipboardItem? {
        // Respect privacy: skip content marked sensitive/transient.
        if AppSettings.shared.skipSensitive, isSensitive() {
            return nil
        }

        let app = NSWorkspace.shared.frontmostApplication
        let appName = app?.localizedName
        let appIcon = app?.icon

        // 1. File URLs.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], let first = urls.first {
            return ClipboardItem(
                kind: .file,
                text: first.path,
                fileURL: first,
                sourceAppName: appName,
                sourceAppIcon: appIcon
            )
        }

        // 2. Images.
        if let images = pasteboard.readObjects(forClasses: [NSImage.self]) as? [NSImage],
           let image = images.first,
           pasteboard.string(forType: .string) == nil {
            if let url = cacheImage(image) {
                return ClipboardItem(
                    kind: .image,
                    fileURL: url,
                    sourceAppName: appName,
                    sourceAppIcon: appIcon
                )
            }
        }

        // 3. Text (and derived link / color).
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind = classifyText(string)
            return ClipboardItem(
                kind: kind,
                text: string,
                sourceAppName: appName,
                sourceAppIcon: appIcon
            )
        }

        return nil
    }

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0) }
    }

    func toggleFavorite(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].isFavorite.toggle()
        persist()
    }

    func addTag(_ tag: String, to item: ClipboardItem) {
        let clean = tag.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty, let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        if !items[idx].tags.contains(where: { $0.caseInsensitiveCompare(clean) == .orderedSame }) {
            items[idx].tags.append(clean)
            persist()
        }
    }

    func removeTag(_ tag: String, from item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].tags.removeAll { $0 == tag }
        persist()
    }

    /// All distinct tags currently in use, sorted.
    var allTags: [String] {
        var seen = Set<String>()
        var result: [String] = []
        for item in items {
            for tag in item.tags where !seen.contains(tag.lowercased()) {
                seen.insert(tag.lowercased())
                result.append(tag)
            }
        }
        return result.sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
    }

    private func classifyText(_ text: String) -> ClipboardItem.Kind {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if NSColor.looksLikeColor(trimmed) { return .color }
        if let url = URL(string: trimmed),
           let scheme = url.scheme,
           ["http", "https"].contains(scheme.lowercased()),
           !trimmed.contains(" ") {
            return .link
        }
        return .text
    }

    private func insert(_ item: ClipboardItem) {
        // Deduplicate consecutive identical text payloads.
        if let text = item.text, let first = items.first,
           first.text == text, first.kind == item.kind {
            return
        }
        items.insert(item, at: 0)
        trimIfNeeded()
        persist()
        onCapture?(item)
    }

    /// Trims to maxItems but never drops favorites.
    private func trimIfNeeded() {
        guard items.count > maxItems else { return }
        var kept: [ClipboardItem] = []
        var nonFavoriteCount = 0
        for item in items {
            if item.isFavorite {
                kept.append(item)
            } else if nonFavoriteCount < maxItems {
                kept.append(item)
                nonFavoriteCount += 1
            } else if let url = item.fileURL {
                try? FileManager.default.removeItem(at: url)
            }
        }
        items = kept
    }

    private func cacheImage(_ image: NSImage) -> URL? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }
        let url = Persistence.cacheDirectory
            .appendingPathComponent("clip-\(UUID().uuidString).png")
        try? png.write(to: url)
        return url
    }

    // MARK: - Persistence

    private struct StoredItem: Codable {
        let id: UUID
        let kind: ClipboardItem.Kind
        let createdAt: Date
        let text: String?
        let fileName: String?
        var isFavorite: Bool = false
        var tags: [String] = []
    }

    private func persist() {
        let stored = items.map { item in
            StoredItem(
                id: item.id,
                kind: item.kind,
                createdAt: item.createdAt,
                text: item.text,
                fileName: item.fileURL?.lastPathComponent,
                isFavorite: item.isFavorite,
                tags: item.tags
            )
        }
        Persistence.save(stored, to: Persistence.historyIndexURL)
    }

    private func loadFromDisk() {
        guard let stored = Persistence.load([StoredItem].self, from: Persistence.historyIndexURL) else {
            return
        }
        items = stored.compactMap { s in
            var fileURL: URL?
            if let name = s.fileName {
                let candidate = Persistence.cacheDirectory.appendingPathComponent(name)
                fileURL = FileManager.default.fileExists(atPath: candidate.path) ? candidate : nil
            }
            // Drop entries whose cached file vanished.
            if (s.kind == .image || s.kind == .file) && fileURL == nil { return nil }
            return ClipboardItem(
                id: s.id,
                kind: s.kind,
                createdAt: s.createdAt,
                text: s.text,
                fileURL: fileURL,
                isFavorite: s.isFavorite,
                tags: s.tags
            )
        }
    }
}
